"""per-website SFTP sub-accounts

Revision ID: 0032_sftp_accounts
Revises: 0031_website_crs_enabled
Create Date: 2026-09-21

Until now a panel user had exactly one SFTP login - their own Linux account,
chrooted to /home/<user>, with the panel password. Handing that to a freelancer
hands over every website the account owns, and the panel password with it.

This table records sub-accounts: extra SFTP logins, each pinned to one website.

owner_id is denormalised rather than read through website_id. It is what the
teardown sweep filters on, and websites.owner_id can change when a site is
transferred - the sub-account must follow the site, not the original owner, so
the two are written together by the API rather than inferred from each other.

No foreign key is emitted on SQLite (the shipped backend) for the same reason
0014 did not: PRAGMA foreign_keys is off there, so the constraint would be
decorative. The deletion paths sweep explicitly instead - see
app/services/teardown.py.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "0032_sftp_accounts"
down_revision: Union[str, None] = "0031_website_crs_enabled"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "sftp_accounts",
        sa.Column("id", sa.Integer(), primary_key=True, index=True),
        sa.Column("owner_id", sa.Integer(), nullable=False, index=True),
        sa.Column("website_id", sa.Integer(), nullable=False, index=True),
        # The label the user typed, shown in the UI. Not the login name.
        sa.Column("label", sa.String(length=32), nullable=False),
        # The actual Linux user, which is what they type into an SFTP client.
        # Generated, unique, and 32 characters at most because that is the
        # Linux limit.
        sa.Column("linux_user", sa.String(length=32), nullable=False, unique=True, index=True),
        # Absolute path of the root-owned chroot. Stored so teardown can remove
        # exactly what was created rather than recomputing a path that may have
        # been generated by an older version of the naming rule.
        sa.Column("chroot_path", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="1"),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column("password_set_at", sa.DateTime(), nullable=True),
    )
    op.create_index(
        "ix_sftp_accounts_owner_label",
        "sftp_accounts",
        ["owner_id", "website_id", "label"],
        unique=True,
    )

    # Gated off by default, exactly like node_apps_limit: a second credential
    # into a customer's files is not something to hand out implicitly, and
    # unlike terminal_enabled there is no existing behaviour to preserve -
    # nobody has these accounts yet, so there is nothing to backfill.
    op.add_column(
        "user_packages",
        sa.Column("sftp_accounts_limit", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "users",
        sa.Column("sftp_accounts_limit", sa.Integer(), nullable=False, server_default="0"),
    )


def downgrade() -> None:
    op.drop_column("users", "sftp_accounts_limit")
    op.drop_column("user_packages", "sftp_accounts_limit")
    op.drop_index("ix_sftp_accounts_owner_label", table_name="sftp_accounts")
    op.drop_table("sftp_accounts")
